### ISSUE TITLE
没有重试日志输出

### ISSUE THREAD

**Issue by zyfmix** [fleeto/istio-for-beginner#1]
第 118 页实测 `kubectl logs -f httpbin-xx -c istio-proxy` 没有请求日志输出问题。
环境:
Istio 1.1.7 
Kubernetes 1.14.1

**Comment by fleeto** [comment]
多谢，我明天会试一下

**Comment by fleeto** [comment]
https://blog.fleeto.us/post/istio-book-update-for-1-1/

突然想起来，答案在这里，Istio 1.0 升级到 1.1 之后，有部分缺省行为发生了变化。
